# Generated by Django 5.1.6 on 2025-02-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_todo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='data',
            new_name='date',
        ),
    ]
